- [/uas4/rpy_deg, Vector3, rpy_deg]
- [/uas4/dji_sdk/gps_position, NavSatFix, gps_fix]
- [/uas4/uaspose, PoseStamped, uaspose]
- [/uas4/currentgoal_enu, currentgoal, currentgoal_enu]
- [/tag_detections, AprilTagDetectionArray, tag_detectionsArray]
- [/uas4/dji_sdk/imu, Imu, imu_data]
- [/uas4/dji_sdk/rc, Joy, rc]
- [/uas4/dji_sdk/flight_control_setpoint_generic, Joy, cmd_vel_joy]
- [/uas4/dji_sdk/velocity, Vector3Stamped, velocity]
#- ['/uas4/dji_sdk/height_above_takeoff',Float32,fusedHeight]
#- ['/uas4/dji_sdk/flight_status',UInt8,flight_status]
#- ['/uas4/basegoal_enuMarker',PoseArray,basegoalArray_enu]
#- ['/camera_array/cam0/camera_info',CameraInfo,CameraInfoMsg]
#- ['/camera_array/cam0/image_raw',Image,images]